### PR TITLE
feat(Angular2): conversion complete :)

### PR DESCRIPTION
**Pull request by NathanWalker**
closes https://github.com/juristr/juristr.github.com/issues/5

### CODE REVIEW

**Comment by juristr** [comment]
Really cool :clap: 

Gave it a quick look as I couldn't resist. I'll merge it in tonight probably. And I'll definitely come back to you for some feedback on my Angular 2 screencast series (1st draft outline should be done in the next couple of days).

Meanwhile, thx!

**Comment by NathanWalker** [comment]
Thanks. And we should definitely mention ng2-play repo in Readme as the
setup is based off that. Bedtime west coast for me, but if you have any
questions I'll get to them tomorrow.

**Comment by juristr** [comment]
:+1: for ng2-play. Haven't yet seen that, but might definitely turn out to be useful in the future :smile: Thx!

**Comment by NathanWalker** [comment]
Just added a line about setup using ng2-play.

**Comment by juristr** [comment]
@NathanWalker cool, unfortunately I wasn't yet able to give it a look :unamused: Hopefully today after work.

The preparation of the draft outline for my Angular 2 screencast series is sucking up all my free time right now. Oh, btw, if u follow me on Twitter, I could DM you the draft outline. I'm always interested in getting some feedback if you don't mind :smile:

**Comment by NathanWalker** [comment]
No worries, I totally understand. Excited to check out your draft outline for sure, I'll look out for it :+1:

**Comment by juristr** [comment]
@NathanWalker had to do some adjustments (due to the deployment nature of Jekyll on GitHub pages).
- moving everything dev specific to `_dev` subfolder as `_` prefixed folders won't get deployed by Jekyll
- copying the stuff to be actually deployed to the `https://github.com/juristr/juristr.github.com/tree/master/apps/ng2beta` folder.

Currently it's done manually (due to lack of time) but I'd like to automate the compilation of the distribution with gulp s.t. you run `gulp build` and it copies all of the required files into a `release` folder (minified into a single file, also copying the dependencies from `node_modules`).

**Comment by juristr** [comment]
@NathanWalker but it's online now :+1: :smile:

**Comment by NathanWalker** [comment]
Nice work @juristr!

**Comment by juristr** [comment]
@NathanWalker Well, it was u working, I didn't do much :wink:

**Pull request closed without merging**
